"""Build a board-meeting preparation concept using the existing native brand shell."""
from pathlib import Path
from urllib.parse import urlsplit
from bs4 import BeautifulSoup
import html, json, os
ROOT=Path(__file__).resolve().parents[1]
PATH='guides/tools/board-deck-builder.html'
BASE='https://credyset.github.io/centripetal-advisors-site/'
DATA=json.loads((ROOT/'tools/board-builder-content.json').read_text())
e=lambda s:html.escape(s,quote=True)
soup=BeautifulSoup((ROOT/'guides/saas-cash-flow-mistakes.html').read_text(),'html.parser')
for node in soup.select('[href],[src]'):
 for attr in ('href','src'):
  value=node.get(attr)
  if not value or value.startswith(('#','//')) or urlsplit(value).scheme:continue
  p=urlsplit(value)
  node[attr]=os.path.relpath((ROOT/'guides'/p.path).resolve(),(ROOT/PATH).parent)+('?' +p.query if p.query else '')+('#'+p.fragment if p.fragment else '')
for node in soup.select('script[src*="cash-review"],link[href*="cash-guide-reference"],.guide-editorial'):node.decompose()
title='Board Deck Structure Builder | Centripetal Advisors'
desc='Build a board-meeting outline around the decision, evidence, assumptions, and owners. Use the review list to organize follow-ups with your team.'
soup.body['class']=['ca-native','ca-board-tool-reference']
soup.title.string=title
for attr,key,value in [('name','description',desc),('property','og:title',title),('property','og:description',desc),('name','twitter:title',title),('name','twitter:description',desc),('property','og:url',BASE+PATH)]:
 node=soup.find('meta',attrs={attr:key})
 if node:node['content']=value
soup.find('link',rel='canonical')['href']=BASE+PATH
schema=json.loads(soup.find('script',type='application/ld+json').string)
graph=[x for x in schema['@graph'] if x['@type'] in ['Organization','WebSite']]
graph+=[{'@type':'WebPage','@id':BASE+PATH+'#page','name':title,'url':BASE+PATH,'description':desc,'isPartOf':{'@id':BASE+'#website'}},{'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':i+1,'name':label,'item':BASE+dest} for i,(label,dest) in enumerate([('Home',''),('Resources','resources/index.html'),('Guides & Tools','guides/index.html'),('Board Deck Structure Builder',PATH)])]}]
soup.find('script',type='application/ld+json').string=json.dumps({'@context':'https://schema.org','@graph':graph},ensure_ascii=False)
for a in soup.select('.site-nav a'):
 a.attrs.pop('aria-current',None)
 if a.get_text(strip=True) in ['Blogs','Blog']:a.string='Blog'
 if a.get_text(strip=True)=='Resources':a['aria-current']='page'
def section(content,stone=False,wide=False):
 return '<section class="ca-section'+(' ca-stone' if stone else '')+'"><div class="ca-inner">'+('' if wide else '<div class="ca-guide-article ca-board-reading">')+content+('' if wide else '</div>')+'</div></section>'
body='<header class="concept-hero"><div class="concept-hero-inner"><p class="eyebrow">Board &amp; investor reporting · Preparation tool</p><h1>Board Deck Structure Builder</h1><p>Build the meeting around the decision, not the slide count.</p></div></header>'
body+=section('<nav class="ca-board-breadcrumb" aria-label="Breadcrumb"><a href="../../resources/index.html">Resources</a><span aria-hidden="true">/</span><a href="../index.html">Guides &amp; Tools</a><span aria-hidden="true">/</span><span>Board Deck Builder</span></nav><div class="ca-board-purpose-grid"><div><h2 id="purpose" tabindex="-1">What should a board deck help the board decide?</h2><p>A useful board deck connects management’s recommendation to operating evidence, the assumption that could change it, and the people who own the response. This builder turns the meeting focus into a preparation outline and discussion prompts.</p><p class="ca-board-scope">For board meetings and operating updates. It organizes preparation; it does not generate presentation slides or verify readiness.</p></div><aside><p class="ca-eyebrow">Working concept</p><p>Framework and wording for firm review. Choose the main discussion, then adapt the outline to your agenda.</p><a class="ca-link" href="#builder">Build your outline →</a></aside></div><nav class="ca-board-utility" aria-label="On this page"><a href="#builder">Builder</a><a href="#framework">Evidence framework</a><a href="#questions">Questions &amp; sources</a><button class="ca-print-button" hidden type="button">Print this page</button></nav>',wide=True)
focus=DATA['focuses'][0]
options=''.join(f'<label><input type="radio" name="board-focus" value="{f["id"]}"'+(' checked' if i==0 else '')+f'><span>{e(f["label"])}</span></label>' for i,f in enumerate(DATA['focuses']))
fields='<fieldset class="ca-review-field"><legend>Main discussion</legend><p>Choose the focus to add to the outline. Every focus keeps the same core evidence framework.</p><div class="ca-review-options">'+options+'</div></fieldset>'
fields+='<fieldset class="ca-review-field"><legend>What do you need from the board?</legend><p>Choose how to frame the opening request. This does not determine formal approval requirements.</p><div class="ca-review-options"><label><input type="radio" name="board-request" value="input" checked><span>Input on a recommendation</span></label><label><input type="radio" name="board-request" value="decision"><span>A decision on a proposal</span></label></div></fieldset>'
fields+='<p><a class="ca-link" href="#board-outline">View working outline →</a></p><details class="ca-board-checklist"><summary>Review supporting evidence (optional)</summary><p>“Reviewed” records your check; it does not verify the evidence. Follow-ups remain visible even when the outline is complete.</p>'
for s in DATA['sections']:
 fields+=f'<fieldset class="ca-review-field" data-board-area="{s["id"]}" data-title="{e(s["title"])}"><legend>{e(s["title"])}</legend><p>{e(s["evidence"])}</p><div class="ca-review-options">'+''.join(f'<label><input type="radio" name="board-review-{s["id"]}" value="{value}"'+(' checked' if value=='pending' else '')+f'><span>{label}</span></label>' for value,label in [('reviewed','Reviewed'),('followup','Follow-up needed'),('pending','Not reviewed')])+'</div></fieldset>'
fields+='</details>'
outline=''
labels={'decision':'Decision & recommendation','changes':'Changes since the last meeting','cash':'Cash & commitments','definitions':'Metric definitions & sources','owners':'Owners & dependencies','followup':'Actions & next review'}
for i,s in enumerate(DATA['sections']):
 if i==2:outline+=f'<li data-board-focus-outline><a href="#focus-evidence">{e(focus["title"])}</a></li>'
 outline+=f'<li><a href="#{s["id"]}">{e(labels[s["id"]])}</a></li>'
result='<aside class="ca-review-panel" id="board-outline" tabindex="-1" aria-label="Your board meeting preparation"><h3>Your working outline</h3><p data-board-opening>Open with the recommendation, the alternatives, and the input you want from the board.</p><ol class="ca-board-outline">'+outline+'</ol><div data-board-focus-result><h3>'+e(focus['title'])+'</h3><p>'+e(focus['body'])+'</p><p><strong>Evidence to bring:</strong> '+e(focus['evidence'])+'</p><p><strong>Discussion prompt:</strong> '+e(focus['question'])+'</p></div><div data-board-review-result hidden><h3>Your follow-up list</h3><p role="status" aria-live="polite" data-board-status></p><details class="ca-board-followup-details"><summary>See the evidence follow-ups</summary><ul data-board-followups></ul></details><p data-board-empty hidden>All six areas are marked reviewed. Keep the evidence, owners, and next review dates alongside the deck; completing this list is not a readiness verdict.</p><details class="ca-preparation-note"><summary>Use this outline in your meeting preparation</summary><label for="board-preparation-note">Preparation note · updates with your selections</label><textarea id="board-preparation-note" data-board-note readonly rows="12"></textarea><button type="button" data-copy-note>Copy preparation note</button><p role="status" data-copy-status></p></details><button type="button" data-board-reset>Reset outline &amp; review</button></div></aside>'
body+='<section class="ca-section ca-cash-review ca-board-builder" data-board-builder><div class="ca-inner"><h2 id="builder" tabindex="-1">Organize the conversation and its evidence.</h2><p class="ca-intro">Choose the main discussion and the request. The outline updates as you work; the evidence review is optional. Selections are not saved or submitted.</p><noscript><p>The operating-plan outline below is a static example. Enable JavaScript to change the outline and generate a follow-up list; the supporting framework remains readable below.</p></noscript><div class="ca-split"><div>'+fields+'</div>'+result+'</div></div></section>'
evidence='<h2 id="framework" tabindex="-1">The evidence behind the outline.</h2><p class="ca-intro">Use the six areas to connect the recommendation to its support. Detailed evidence and discussion prompts sit with each area.</p><div class="ca-board-evidence-grid">'
for i,item in enumerate(DATA['sections']):
 evidence+=f'<article class="ca-board-evidence-item"><p class="ca-eyebrow">{i+1:02d} · Core evidence</p><h3 id="{item["id"]}" tabindex="-1">{e(item["title"])}</h3><p>{e(item["body"])}</p><details><summary>Evidence and discussion prompt</summary><p><strong>Evidence to bring:</strong> {e(item["evidence"])}</p><p><strong>Discussion prompt:</strong> {e(item["question"])}</p></details></article>'
body+=section(evidence+'</div>',wide=True)
body+=section('<div class="ca-guide-example"><p class="ca-eyebrow">Illustrative preparation · no client results</p><h2>A signed contract supports a hire. Implementation moves.</h2><p>Suppose a new subscription is signed, but its start date moves and the expected receipt depends on an implementation milestone. The deck shows contracted growth; the hiring recommendation depends on the timing behind it.</p><dl><div><dt>The request</dt><dd>Ask for input on starting the hire now or waiting for the milestone. Show management’s recommendation and the consequence of each choice.</dd></div><div><dt>The evidence bridge</dt><dd>Keep contracted and live recurring revenue distinct. Connect the customer’s start and payment assumptions to the hiring commitment in the cash plan, with the reporting cutoff stated.</dd></div><div><dt>The owner and next review</dt><dd>Name who confirms the implementation milestone and who refreshes the cash assumption. Set the condition and review date that would reopen the hiring decision.</dd></div></dl><p>The board conversation is about the commitment and its dependency. More revenue slides alone would not resolve that question.</p></div>')
body+=section('<h2 id="focus-evidence" tabindex="-1">Add the evidence for the main discussion.</h2><p>Use the relevant focus alongside the core outline. A financing conversation in a board meeting still needs an operating recommendation; use the separate diligence framework for an investor evidence process.</p>'+''.join(f'<details><summary>{e(f["label"])}</summary><h3>{e(f["title"])}</h3><p>{e(f["body"])}</p><p><strong>Evidence to bring:</strong> {e(f["evidence"])}</p><p><strong>Discussion prompt:</strong> {e(f["question"])}</p></details>' for f in DATA['focuses']))
body+=section('<h2 id="questions" tabindex="-1">Questions before you build the slides.</h2><details><summary>Does the outline replace the existing board agenda?</summary><p>No. Adapt it to the meeting’s purpose and the board’s agreed agenda. Use the preparation list to find missing evidence, owners, or questions, rather than adding every possible metric to the deck.</p></details><details><summary>Who should own each section?</summary><p>Assign the relevant operating leader to the result and proposed response. Agree who checks the numbers, integrates the narrative, and maintains the action log. The tool does not allocate those responsibilities for your company.</p></details><details><summary>What changes for an investor update or fundraising pitch?</summary><p>An investor update may communicate progress and requests without a formal board decision. A fundraising pitch connects the capital ask to the operating story and supporting diligence. Use the <a class="ca-link" href="../series-a-diligence-readiness.html">Series A diligence guide</a> for that evidence review.</p></details><div class="ca-guide-sources"><h3>Source and related frameworks</h3><p><a href="https://stripe.com/resources/more/committed-annual-recurring-revenue-explained">Stripe · Contracted recurring revenue, ARR, and recognized revenue</a> supports the metric distinctions. The outline and discussion prompts are an editorial preparation framework for firm review; they do not predict what a particular board will ask.</p><p><a class="ca-link" href="../saas-cash-flow-mistakes.html">Review cash assumptions →</a></p><p><a class="ca-link" href="../../services/board-investor-reporting.html">Explore board &amp; investor reporting support →</a></p></div>',True)
body+=section('<p class="ca-eyebrow">Connect the preparation to your company</p><h2>What does the next board conversation need to resolve?</h2><p class="ca-intro">Start with the decision, meeting timing, and evidence that needs attention. Your tool selections are not included in the conversation link.</p><a class="pill-button" href="../../contact.html?topic=board-reporting&amp;from=tool-board-deck-builder#conversation-form">Discuss your board reporting →</a><p class="ca-footer">Related article concept: <a class="ca-link" href="../../blog/board-reporting-seed-series-a.html">Which decision should your board package support? →</a></p>',wide=True)
soup.main.clear();soup.main.append(BeautifulSoup(body,'html.parser'))
node=soup.new_tag('script',type='application/json',id='board-builder-data');node.string=json.dumps(DATA,ensure_ascii=False).replace('<','\\u003c');soup.body.append(node)
script=soup.new_tag('script',src='../../assets/board-builder.js?v=20261009-3',defer='');soup.body.append(script)
css=soup.new_tag('link',href='../../assets/board-builder.css?v=20261009-5',rel='stylesheet');soup.head.append(css)
(ROOT/PATH).write_text(str(soup).rstrip()+'\n')
